In [135]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [155]:
df = pd.read_csv('xAPI-Edu-Data.csv')
df

gender NationalITy PlaceofBirth       StageID GradeID SectionID  \
0        M          KW       KuwaIT    lowerlevel    G-04         A   
1        M          KW       KuwaIT    lowerlevel    G-04         A   
2        M          KW       KuwaIT    lowerlevel    G-04         A   
3        M          KW       KuwaIT    lowerlevel    G-04         A   
4        M          KW       KuwaIT    lowerlevel    G-04         A   
..     ...         ...          ...           ...     ...       ...   
475      F      Jordan       Jordan  MiddleSchool    G-08         A   
476      F      Jordan       Jordan  MiddleSchool    G-08         A   
477      F      Jordan       Jordan  MiddleSchool    G-08         A   
478      F      Jordan       Jordan  MiddleSchool    G-08         A   
479      F      Jordan       Jordan  MiddleSchool    G-08         A   

         Topic Semester Relation  raisedhands  VisITedResources  \
0           IT        F   Father           15                16   
1           IT        F   Father           20                20   
2           IT        F   Father           10                 7   
3           IT        F   Father           30                25   
4           IT        F   Father           40                50   
..         ...      ...      ...          ...               ...   
475  Chemistry        S   Father            5                 4   
476    Geology        F   Father           50                77   
477    Geology        S   Father           55                74   
478    History        F   Father           30                17   
479    History        S   Father           35                14   

     AnnouncementsView  Discussion ParentAnsweringSurvey  \
0                    2          20                   Yes   
1                    3          25                   Yes   
2                    0          30                    No   
3                    5          35                    No   
4                   12          50                    No   
..                 ...         ...                   ...   
475                  5           8                    No   
476                 14          28                    No   
477                 25          29                    No   
478                 14          57                    No   
479                 23          62                    No   

    ParentschoolSatisfaction StudentAbsenceDays Class  
0                       Good            Under-7     M  
1                       Good            Under-7     M  
2                        Bad            Above-7     L  
3                        Bad            Above-7     L  
4                        Bad            Above-7     M  
..                       ...                ...   ...  
475                      Bad            Above-7     L  
476                      Bad            Under-7     M  
477                      Bad            Under-7     M  
478                      Bad            Above-7     L  
479                      Bad            Above-7     L  

[480 rows x 17 columns]

In [137]:
df_ = df[['PlaceofBirth','raisedhands','ParentschoolSatisfaction']]
df_

PlaceofBirth  raisedhands ParentschoolSatisfaction
0         KuwaIT           15                     Good
1         KuwaIT           20                     Good
2         KuwaIT           10                      Bad
3         KuwaIT           30                      Bad
4         KuwaIT           40                      Bad
..           ...          ...                      ...
475       Jordan            5                      Bad
476       Jordan           50                      Bad
477       Jordan           55                      Bad
478       Jordan           30                      Bad
479       Jordan           35                      Bad

[480 rows x 3 columns]

In [138]:
Nominal_data = df_[['PlaceofBirth']]
Numerical_data = df_[['raisedhands']]
Ordinal_data = df_[['ParentschoolSatisfaction']]

# NOMINAL DATA

In [139]:
Nominal_data

PlaceofBirth
0         KuwaIT
1         KuwaIT
2         KuwaIT
3         KuwaIT
4         KuwaIT
..           ...
475       Jordan
476       Jordan
477       Jordan
478       Jordan
479       Jordan

[480 rows x 1 columns]

In [140]:
from sklearn.model_selection import train_test_split
Nominal_data_, _ = train_test_split(Nominal_data, test_size=0.988)
Nominal_data_

PlaceofBirth
450       Jordan
136          USA
3         KuwaIT
249       KuwaIT
285       Jordan

In [153]:
def diss_nom(a,b):
    if a==b:
        return 0
    return 1
array_ = np.array(Nominal_data_['PlaceofBirth'])
l = len(array_)
dmnom = np.empty((l,l),int)
print("Dissimilarity Matrix for Nominal Data: ")
for i in range(l):
    for j in range(i+1):
        dmnom[i][j] = diss_nom(array_[i],array_[j])
dmnom

#for similarity matrix: sil=(1-dis)

Dissimilarity Matrix for Nominal Data: 


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0]])

# NUMERICAL DATA

In [142]:
Numerical_data

raisedhands
0             15
1             20
2             10
3             30
4             40
..           ...
475            5
476           50
477           55
478           30
479           35

[480 rows x 1 columns]

In [143]:
Numerical_data_, _ = train_test_split(Numerical_data, test_size=0.98)
Numerical_data_

raisedhands
95           100
314           78
347           23
99            50
250           15
302           11
173           20
63            17
124            0

In [160]:
maxh = max(Numerical_data_['raisedhands'])
minh = min(Numerical_data_['raisedhands'])

array_ = np.array(Numerical_data_['raisedhands'])
l = len(array_)
dmnum = np.empty((l,l),float)
print("Dissimilarity Matrix for Numerical Data: ")
for i in range(0,l):
    for j in range(i+1,l):
        dmnum[j][i] = abs(array_[i]-array_[j])/(maxh-minh)
        dmnum[i][j] = 0
dmnum

Dissimilarity Matrix for Numerical Data: 


array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.22, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.77, 0.55, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.5 , 0.28, 0.27, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.85, 0.63, 0.08, 0.35, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.89, 0.67, 0.12, 0.39, 0.04, 0.  , 0.  , 0.  , 0.  ],
       [0.8 , 0.58, 0.03, 0.3 , 0.05, 0.09, 0.  , 0.  , 0.  ],
       [0.83, 0.61, 0.06, 0.33, 0.02, 0.06, 0.03, 0.  , 0.  ],
       [1.  , 0.78, 0.23, 0.5 , 0.15, 0.11, 0.2 , 0.17, 0.  ]])

# ORDINAL DATA

In [145]:
Ordinal_data

ParentschoolSatisfaction
0                       Good
1                       Good
2                        Bad
3                        Bad
4                        Bad
..                       ...
475                      Bad
476                      Bad
477                      Bad
478                      Bad
479                      Bad

[480 rows x 1 columns]

In [146]:
Ordinal_data['ParentschoolSatisfaction'].replace({'Good':1, 'Bad':0}, inplace= True)
Ordinal_data

C:\Users\Hardik Maisuria\anaconda3\lib\site-packages\pandas\core\series.py:4563: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(


ParentschoolSatisfaction
0                           1
1                           1
2                           0
3                           0
4                           0
..                        ...
475                         0
476                         0
477                         0
478                         0
479                         0

[480 rows x 1 columns]

In [147]:
Ordinal_data_, _ = train_test_split(Ordinal_data, test_size=0.988, stratify=Ordinal_data['ParentschoolSatisfaction'])
Ordinal_data_

ParentschoolSatisfaction
390                         1
259                         0
353                         1
179                         0
466                         1

In [152]:
def diss_o(a, b):
    return abs(a-b)
array_ = np.array(Ordinal_data_['ParentschoolSatisfaction'])
l = len(array_)
dmo = np.empty((l,l),int)
print("Dissimilarity Matrix for Ordinal Data: ")
for i in range(l):
    for j in range(i+1):
        dmo[i][j] = diss_o(array_[i],array_[j])
dmo

Dissimilarity Matrix for Ordinal Data: 


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0]])