In [1]:
import pandas as pd
import numpy as np

dataset = {'SBP':[126,128,128,130,130,132],'DBP':[78,80,82,82,84,86]}   #loading the dataset
dataset = pd.DataFrame(dataset)
d_copy = np.copy(np.array(dataset))
dataset.head()

SBP  DBP
0  126   78
1  128   80
2  128   82
3  130   82
4  130   84

In [2]:
clm = list(dataset.columns)     #calculating mean for each column
dataset_mean=[]
for i in range(dataset.shape[1]):
    dataset_mean.append(round((dataset[clm[i]].mean()),2))
dataset_mean

[129.0, 82.0]

In [3]:
for i in range(dataset.shape[1]):      #step-1 : centering the values(minus the mean from each cell)
    for j in range(dataset.shape[0]):
        dataset.iloc[j][i] = dataset.iloc[j][i] - dataset_mean[i]
dataset.head()

SBP  DBP
0   -3   -4
1   -1   -2
2   -1    0
3    1    0
4    1    2

In [4]:
covariance = np.cov(dataset.T)    #step-2 : calculating covariance matrix
covariance

array([[4.4, 5.6],
       [5.6, 8. ]])

In [5]:
eigen_values, eigen_vectors = np.linalg.eig(covariance)    #step-3,4 : calculating eigun values and eigun vectors
print("Eigun Values are : ",eigen_values)
print("Eigun Vectors are : ",eigen_vectors)

Eigun Values are :  [ 0.31782353 12.08217647]
Eigun Vectors are :  [[-0.80808699 -0.58906316]
 [ 0.58906316 -0.80808699]]


In [6]:
d = np.argsort(np.array(eigen_values))    #step-5 : Ordering the Eigun Vectors
d = d[::-1]
d_eigenvalues = eigen_values[d]
d_eigenvectors = eigen_vectors[:,d]
eigen_vector_subset = d_eigenvectors[:,:]
print(eigen_vector_subset)

[[-0.58906316 -0.80808699]
 [-0.80808699  0.58906316]]


In [7]:
fv = np.dot(eigen_vector_subset.T , dataset.T ).T   #step-6 : Calculating the principal component(PC1,PC2)
print(fv)

[[ 4.99953747  0.06800833]
 [ 2.20523715 -0.37003933]
 [ 0.58906316  0.80808699]
 [-0.58906316 -0.80808699]
 [-2.20523715  0.37003933]
 [-4.99953747 -0.06800833]]


In [8]:
vari = pd.DataFrame(fv,columns=['PC1','PC2'])
print(vari)
for i in vari.columns:
    print("variance for ",i,"is ",vari[i].var())

        PC1       PC2
0  4.999537  0.068008
1  2.205237 -0.370039
2  0.589063  0.808087
3 -0.589063 -0.808087
4 -2.205237  0.370039
5 -4.999537 -0.068008
variance for  PC1 is  12.082176467941096
variance for  PC2 is  0.3178235320589029


Since, PC2 has lower value of variance than PC1, we select PC1, as it gives us more values and precise information about our dataset

# Conclusion

From this practical we can learn to find the optimize value of alpha1 and alpha2 using PCA for which the final output BP is calculated. It can be used to reduce number of variables in your data by extracting important one from large pool and it also simplifies the complexity in high dimensional data while retaining the trends and patterns.